[workspace]
members = [
    "packages/utils",
    "packages/test_utils",
    "packages/message",
    "packages/components",
    "packages/message_transmitter",
    "packages/token_messenger_minter",
    "packages/interfaces"
]

[workspace.package]
version = "0.1.0"
edition = "2024_07"
cairo-version = "2.12.0"
scarb-version = "2.12.0"
authors = ["Circle"]
description = "CCTP Contracts Starknet"
homepage = "https://www.circle.com"
license-file = "LICENSE"
repository = "https://github.com/circlefin/starknet-cctp"
documentation = "https://developers.circle.com/starknet/docs"
keywords = [
    "starknet",
    "cctp",
    "contracts"
]

[workspace.dependencies]
assert_macros = "2.12.0"
starknet = "2.12.0"
snforge_std = "0.48.1"
utils = { path = "packages/utils" }
test_utils = { path = "packages/test_utils" }
message = { path = "packages/message" }
cctp_components = { path = "packages/components" }
interfaces = { path = "packages/interfaces" }
message_transmitter = { path = "packages/message_transmitter" }
token_messenger_minter = { path = "packages/token_messenger_minter" }
components = { path = "stablecoin-starknet-private/packages/components" }
stablecoin = { path = "stablecoin-starknet-private/packages/stablecoin" }

[workspace.tool.fmt]

[workspace.tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

# Required for generating coverage report
[profile.dev.cairo]
unstable-add-statements-functions-debug-info = true
unstable-add-statements-code-locations-debug-info = true
inlining-strategy = "avoid"
